const dummyData = {
  categories: [
    { name: "Burgers", description: "Burgers grillés juteux" },
    { name: "Pizzas", description: "Pizzas au fromage cuites au four" },
    { name: "Burritos", description: "Délices mexicains roulés" },
    { name: "Sandwiches", description: "Sandwichs empilés et garnis" },
    { name: "Wraps", description: "Wraps roulés pleins de saveurs" },
    { name: "Bowls", description: "Bols équilibrés de riz et protéines" },
  ],

  customizations: [
    // Garnitures
    { name: "Fromage supplémentaire", price: 25, type: "topping" },
    { name: "Jalapeños", price: 20, type: "topping" },
    { name: "Oignons", price: 10, type: "topping" },
    { name: "Olives", price: 15, type: "topping" },
    { name: "Champignons", price: 18, type: "topping" },
    { name: "Tomates", price: 10, type: "topping" },
    { name: "Bacon", price: 30, type: "topping" },
    { name: "Avocat", price: 35, type: "topping" },

    // Accompagnements
    { name: "Coca", price: 30, type: "side" },
    { name: "Frites", price: 35, type: "side" },
    { name: "Pain à l'ail", price: 40, type: "side" },
    { name: "Nuggets de poulet", price: 50, type: "side" },
    { name: "Thé glacé", price: 28, type: "side" },
    { name: "Salade", price: 33, type: "side" },
    { name: "Potatoes", price: 38, type: "side" },
    { name: "Bâtonnets de mozzarella", price: 45, type: "side" },
    { name: "Maïs doux", price: 25, type: "side" },
    { name: "Gâteau choco-lava", price: 42, type: "side" },
  ],

  menu: [
    {
      name: "Cheeseburger classique",
      description: "Steak de bœuf, fromage, laitue, tomate",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/044/844/600/large_2x/homemade-fresh-tasty-burger-with-meat-and-cheese-classic-cheese-burger-and-vegetable-ai-generated-free-png.png",
      price: 25.99,
      rating: 4.5,
      calories: 550,
      protein: 25,
      category_name: "Burgers",
      customizations: [
        "Fromage supplémentaire",
        "Coca",
        "Frites",
        "Oignons",
        "Bacon",
      ],
    },
    {
      name: "Pizza Pepperoni",
      description: "Garnie de fromage et de tranches de pepperoni",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/023/742/417/large_2x/pepperoni-pizza-isolated-illustration-ai-generative-free-png.png",
      price: 30.99,
      rating: 4.7,
      calories: 700,
      protein: 30,
      category_name: "Pizzas",
      customizations: [
        "Fromage supplémentaire",
        "Jalapeños",
        "Pain à l'ail",
        "Coca",
        "Olives",
      ],
    },
    {
      name: "Burrito aux haricots",
      description: "Garnis de haricots, riz, salsa",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/055/133/581/large_2x/deliciously-grilled-burritos-filled-with-beans-corn-and-fresh-vegetables-served-with-lime-wedge-and-cilantro-isolated-on-transparent-background-free-png.png",
      price: 20.99,
      rating: 4.2,
      calories: 480,
      protein: 18,
      category_name: "Burritos",
      customizations: ["Jalapeños", "Thé glacé", "Frites", "Salade"],
    },
    {
      name: "Burger BBQ Bacon",
      description: "Sauce BBQ fumée, bacon croustillant, cheddar",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/060/236/245/large_2x/a-large-hamburger-with-cheese-onions-and-lettuce-free-png.png",
      price: 27.5,
      rating: 4.8,
      calories: 650,
      protein: 29,
      category_name: "Burgers",
      customizations: ["Oignons", "Frites", "Coca", "Bacon", "Avocat"],
    },
    {
      name: "Wrap César au poulet",
      description: "Poulet grillé, laitue, sauce César",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/048/930/603/large_2x/caesar-wrap-grilled-chicken-isolated-on-transparent-background-free-png.png",
      price: 21.5,
      rating: 4.4,
      calories: 490,
      protein: 28,
      category_name: "Wraps",
      customizations: ["Fromage supplémentaire", "Coca", "Potatoes", "Tomates"],
    },
    {
      name: "Sandwich végétarien grillé",
      description: "Légumes rôtis, pesto, fromage",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/047/832/012/large_2x/grilled-sesame-seed-bread-veggie-sandwich-with-tomato-and-onion-free-png.png",
      price: 19.99,
      rating: 4.1,
      calories: 420,
      protein: 19,
      category_name: "Sandwiches",
      customizations: [
        "Champignons",
        "Olives",
        "Bâtonnets de mozzarella",
        "Thé glacé",
      ],
    },
    {
      name: "Burger double steak",
      description: "Deux steaks de bœuf juteux et fromage",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/060/359/627/large_2x/double-cheeseburger-with-lettuce-tomatoes-cheese-and-sesame-bun-free-png.png",
      price: 32.99,
      rating: 4.9,
      calories: 720,
      protein: 35,
      category_name: "Burgers",
      customizations: [
        "Fromage supplémentaire",
        "Oignons",
        "Frites",
        "Coca",
        "Nuggets de poulet",
      ],
    },
    {
      name: "Wrap Paneer Tikka",
      description: "Paneer épicé, chutney à la menthe, légumes",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/057/913/530/large_2x/delicious-wraps-a-tantalizing-array-of-wraps-filled-with-vibrant-vegetables-succulent-fillings-and-fresh-ingredients-artfully-arranged-for-a-mouthwatering-culinary-experience-free-png.png",
      price: 23.99,
      rating: 4.6,
      calories: 470,
      protein: 20,
      category_name: "Wraps",
      customizations: ["Jalapeños", "Tomates", "Salade", "Frites", "Thé glacé"],
    },
    {
      name: "Bowl burrito mexicain",
      description: "Riz, haricots, maïs, guacamole, salsa",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/057/466/374/large_2x/healthy-quinoa-bowl-with-avocado-tomato-and-black-beans-ingredients-free-png.png",
      price: 26.49,
      rating: 4.7,
      calories: 610,
      protein: 24,
      category_name: "Bowls",
      customizations: ["Avocat", "Maïs doux", "Salade", "Thé glacé"],
    },
    {
      name: "Sandwich poulet épicé",
      description: "Poulet croustillant, sauce épicée, cornichons",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/051/814/008/large_2x/a-grilled-chicken-sandwich-with-lettuce-and-tomatoes-free-png.png",
      price: 24.99,
      rating: 4.3,
      calories: 540,
      protein: 26,
      category_name: "Sandwiches",
      customizations: [
        "Jalapeños",
        "Oignons",
        "Frites",
        "Coca",
        "Gâteau choco-lava",
      ],
    },
    {
      name: "Pizza Margherita classique",
      description: "Tomate, mozzarella, basilic frais",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/058/700/845/large_2x/free-isolated-on-transparent-background-delicious-pizza-topped-with-fresh-tomatoes-basil-and-melted-cheese-perfect-for-food-free-png.png",
      price: 26.99,
      rating: 4.1,
      calories: 590,
      protein: 21,
      category_name: "Pizzas",
      customizations: [
        "Fromage supplémentaire",
        "Olives",
        "Coca",
        "Pain à l'ail",
      ],
    },
    {
      name: "Bowl protéiné",
      description: "Poulet grillé, quinoa, légumes",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/056/106/379/large_2x/top-view-salad-with-chicken-avocado-tomatoes-and-lettuce-free-png.png",
      price: 29.99,
      rating: 4.8,
      calories: 580,
      protein: 38,
      category_name: "Bowls",
      customizations: ["Avocat", "Salade", "Maïs doux", "Thé glacé"],
    },
    {
      name: "Burrito au paneer",
      description: "Cubes de paneer, masala épicé, riz, haricots",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/056/565/254/large_2x/burrito-with-cauliflower-and-vegetables-free-png.png",
      price: 24.99,
      rating: 4.2,
      calories: 510,
      protein: 22,
      category_name: "Burritos",
      customizations: ["Jalapeños", "Frites", "Pain à l'ail", "Coca"],
    },
    {
      name: "Club sandwich au poulet",
      description: "Poulet grillé, laitue, fromage, tomate",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/060/364/135/large_2x/a-flavorful-club-sandwich-with-turkey-bacon-and-fresh-vegetables-sliced-and-isolated-on-a-transparent-background-free-png.png",
      price: 27.49,
      rating: 4.5,
      calories: 610,
      protein: 31,
      category_name: "Sandwiches",
      customizations: [
        "Bacon",
        "Tomates",
        "Bâtonnets de mozzarella",
        "Thé glacé",
      ],
    },
  ],
};

export default dummyData;
